### ISSUE TITLE
[dependencies] update checklist

### ISSUE THREAD

**Issue by TFK70** [Atlantis-Lab/nextjs#166]
### Список зависимостей на обновление

- [x] #163 
- [x] #164 

### Блокирующие факторы

В обоих нарушена обратная совместимость, необходим ресёч

**Comment by TFK70** [comment]
@TorinAsakura проблему локализовал - надо импорты поменять, но у меня почему-то локально jest сломался, а в чеках все нормально: https://github.com/Atlantis-Lab/nextjs/runs/1866011240?check_suite_focus=true

TypeError: Cannot read property 'onlyChanged' of undefined
    at _default (/media/darius/6E4CBE7A4CBE3D21/atlantis/nextjs/nextjs/node_modules/jest-cli/node_modules/@jest/core/build/getChangedFilesPromise.js:49:20)
    at /media/darius/6E4CBE7A4CBE3D21/atlantis/nextjs/nextjs/node_modules/jest-cli/node_modules/@jest/core/build/cli/index.js:296:71
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/media/darius/6E4CBE7A4CBE3D21/atlantis/nextjs/nextjs/node_modules/jest-cli/node_modules/@jest/core/build/cli/index.js:108:24)
    at _next (/media/darius/6E4CBE7A4CBE3D21/atlantis/nextjs/nextjs/node_modules/jest-cli/node_modules/@jest/core/build/cli/index.js:128:9)
    at /media/darius/6E4CBE7A4CBE3D21/atlantis/nextjs/nextjs/node_modules/jest-cli/node_modules/@jest/core/build/cli/index.js:133:7
    at new Promise (<anonymous>)
    at /media/darius/6E4CBE7A4CBE3D21/atlantis/nextjs/nextjs/node_modules/jest-cli/node_modules/@jest/core/build/cli/index.js:125:12
    at _run (/media/darius/6E4CBE7A4CBE3D21/atlantis/nextjs/nextjs/node_modules/jest-cli/node_modules/@jest/core/build/cli/index.js:374:20)
    at /media/darius/6E4CBE7A4CBE3D21/atlantis/nextjs/nextjs/node_modules/jest-cli/node_modules/@jest/core/build/cli/index.js:178:13
error Command failed with exit code 1.

В ишью по этому вопросу в основном предлагали обновить то-сё, но тут и так все по сути на последних версиях (мажорные уж точно последние)
Еще предлагали `yarn change policy` до 18, но это во-первых не помогло, а во-вторых на чеках yarn 22.5, так что это не он виноват
Пока продолжу, но проблема прям неочевидная, оказалось

**Comment by TFK70** [comment]
@TorinAsakura проблемы с тестами:
На текущем этапе в этом пре https://github.com/Atlantis-Lab/nextjs/pull/164 не могут пройти тесты в прекоммит хуке, но все проходит локально

### Changelog

#### Были произведены изменения только в двух файлах

**package.json:**

C этого

```javascript
    "emotion-server": "11.0.0",
```

На это 

```javascript
    "emotion-server": "11.0.0",
    "@emotion/server": "^11.0.0",
    "@emotion/css": "^11.1.3",
```

emotion-server решил пока не убирать на данном этапе (как и emotion в этом пре https://github.com/Atlantis-Lab/nextjs/pull/163) чтобы в случае чего не сломалась обратная совместимость, для этого в будущем будет отдельная таска

И в **with-emotion-provider.tsx:**

Заменил импорт с этого:

```javascript
import { extractCritical } from 'emotion-server'
```

На этот:

```javascript
import { extractCritical } from '@emotion/server'
```

Теперь самое главное: после всех `yarn install` и т.д. запускаем `yarn workspace @atlantis-lab/next-document-with-emotion test` и видим следующее:

![image](https://user-images.githubusercontent.com/62806448/107544449-0ed18c80-6bec-11eb-8ea6-0f904365d4d1.png)

**Во-первых,** тест прошел
**Во-вторых,** по запущенному после теста `yarn install` можно убедиться что все действительно "up-to-date"

### Теперь к проблемной части

Теперь осталось все эти изменения закоммитить. Стандартные процедуры: `git add`, `git status` чтобы удостовериться что все ок, ну и `yarn commit`, в процессе которого происходит следующее:

---
TypeError: Class constructor Document cannot be invoked without 'new'


at WithEmotion.MyDoc [as constructor] (packages/next-document-with-emotion/__tests__/with-emotion.test.tsx:53:50)
at new WithEmotion (packages/next-document-with-emotion/src/with-emotion.provider.tsx:23:7)
at Object.tester (packages/next-document-with-emotion/__tests__/with-emotion.test.tsx:31:20)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        0.759 s
---

### Что именно произошло?

Тест, который, как мы удостоверились ранее, проходит, в прекоммит хуке
**Во-первых,** фейлится
**Во-вторых,** следует обратить внимание на эту строку:
`at WithEmotion.MyDoc [as constructor] (packages/next-document-with-emotion/__tests__/with-emotion.test.tsx:53:50)`

Она говорит что ошибка на 53 строке в тесте, когда в самом тесте их 36:

![image](https://user-images.githubusercontent.com/62806448/107545524-370dbb00-6bed-11eb-9942-4967b9e74ff4.png)

Так что не понять какое конкретно место в тесте ему не нравится

Сам тест: https://github.com/Atlantis-Lab/nextjs/blob/master/packages/next-document-with-emotion/__tests__/with-emotion.test.tsx
